spring:
  datasource:
    url: jdbc:mysql://localhost:3306/subway
    username: user
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop